admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: AdminBundle:Default:index }

admin_page:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:admin }

admin_users:
    path:     /admin/{name}
    defaults: { _controller: AdminBundle:Default:hello }